/**
 * The tradeable universe.
 *
 * Doubles as the search index and as seed data for the price cache, so search
 * and trading both work with zero external API calls. Base prices are realistic
 * reference points; the mock provider moves them deterministically from here.
 */
export interface Instrument {
  symbol: string;
  name: string;
  base: number;
  /** Annualised volatility, used to make simulated moves plausibly sized. */
  vol: number;
}

export const INSTRUMENTS: Instrument[] = [
  { symbol: "AAPL", name: "Apple Inc.", base: 232.4, vol: 0.26 },
  { symbol: "ABBV", name: "AbbVie Inc.", base: 178.0, vol: 0.18 },
  { symbol: "ADBE", name: "Adobe Inc.", base: 480.0, vol: 0.27 },
  { symbol: "ADI", name: "Analog Devices Inc.", base: 225.0, vol: 0.24 },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", base: 122.9, vol: 0.45 },
  { symbol: "AMGN", name: "Amgen Inc.", base: 285.0, vol: 0.2 },
  { symbol: "AMZN", name: "Amazon.com Inc.", base: 214.3, vol: 0.31 },
  { symbol: "AVGO", name: "Broadcom Inc.", base: 176.8, vol: 0.38 },
  { symbol: "AXP", name: "American Express Company", base: 290.0, vol: 0.22 },
  { symbol: "BA", name: "The Boeing Company", base: 178.0, vol: 0.38 },
  { symbol: "BAC", name: "Bank of America Corp.", base: 44.0, vol: 0.24 },
  { symbol: "BKNG", name: "Booking Holdings Inc.", base: 4950.0, vol: 0.24 },
  { symbol: "BLK", name: "BlackRock Inc.", base: 980.0, vol: 0.22 },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company", base: 58.0, vol: 0.19 },
  { symbol: "CAT", name: "Caterpillar Inc.", base: 385.0, vol: 0.25 },
  { symbol: "CB", name: "Chubb Limited", base: 285.0, vol: 0.16 },
  { symbol: "CI", name: "The Cigna Group", base: 335.0, vol: 0.21 },
  { symbol: "CMCSA", name: "Comcast Corporation", base: 40.0, vol: 0.21 },
  { symbol: "CME", name: "CME Group Inc.", base: 210.0, vol: 0.16 },
  { symbol: "CMG", name: "Chipotle Mexican Grill Inc.", base: 58.0, vol: 0.27 },
  { symbol: "COF", name: "Capital One Financial Corporation", base: 185.0, vol: 0.28 },
  { symbol: "COP", name: "ConocoPhillips", base: 105.0, vol: 0.26 },
  { symbol: "COST", name: "Costco Wholesale Corporation", base: 921.4, vol: 0.2 },
  { symbol: "CRM", name: "Salesforce Inc.", base: 330.0, vol: 0.29 },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", base: 352.1, vol: 0.42 },
  { symbol: "CSCO", name: "Cisco Systems Inc.", base: 58.0, vol: 0.2 },
  { symbol: "CVS", name: "CVS Health Corporation", base: 62.0, vol: 0.24 },
  { symbol: "CVX", name: "Chevron Corporation", base: 155.0, vol: 0.2 },
  { symbol: "DE", name: "Deere & Company", base: 425.0, vol: 0.24 },
  { symbol: "DHR", name: "Danaher Corporation", base: 250.0, vol: 0.2 },
  { symbol: "DIS", name: "The Walt Disney Company", base: 112.0, vol: 0.24 },
  { symbol: "EL", name: "The Estée Lauder Companies Inc.", base: 68.0, vol: 0.3 },
  { symbol: "EOG", name: "EOG Resources Inc.", base: 118.0, vol: 0.25 },
  { symbol: "FTNT", name: "Fortinet Inc.", base: 92.0, vol: 0.28 },
  { symbol: "GE", name: "GE Aerospace", base: 175.0, vol: 0.24 },
  { symbol: "GILD", name: "Gilead Sciences Inc.", base: 95.0, vol: 0.18 },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", base: 189.6, vol: 0.28 },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", base: 560.0, vol: 0.24 },
  { symbol: "HD", name: "The Home Depot Inc.", base: 398.0, vol: 0.21 },
  { symbol: "HON", name: "Honeywell International Inc.", base: 210.0, vol: 0.18 },
  { symbol: "IBM", name: "International Business Machines Corp.", base: 225.0, vol: 0.19 },
  { symbol: "ICE", name: "Intercontinental Exchange Inc.", base: 155.0, vol: 0.18 },
  { symbol: "INTC", name: "Intel Corporation", base: 24.0, vol: 0.35 },
  { symbol: "INTU", name: "Intuit Inc.", base: 640.0, vol: 0.26 },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", base: 545.0, vol: 0.25 },
  { symbol: "JNJ", name: "Johnson & Johnson", base: 146.2, vol: 0.16 },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", base: 248.5, vol: 0.22 },
  { symbol: "KLAC", name: "KLA Corporation", base: 720.0, vol: 0.3 },
  { symbol: "KO", name: "The Coca-Cola Company", base: 63.0, vol: 0.13 },
  { symbol: "LLY", name: "Eli Lilly and Company", base: 780.0, vol: 0.28 },
  { symbol: "LMT", name: "Lockheed Martin Corporation", base: 480.0, vol: 0.18 },
  { symbol: "LOW", name: "Lowe's Companies Inc.", base: 258.0, vol: 0.19 },
  { symbol: "LRCX", name: "Lam Research Corporation", base: 78.0, vol: 0.34 },
  { symbol: "LULU", name: "Lululemon Athletica Inc.", base: 310.0, vol: 0.33 },
  { symbol: "MCD", name: "McDonald's Corporation", base: 296.0, vol: 0.16 },
  { symbol: "META", name: "Meta Platforms Inc.", base: 604.1, vol: 0.36 },
  { symbol: "MMM", name: "3M Company", base: 132.0, vol: 0.22 },
  { symbol: "MRK", name: "Merck & Co. Inc.", base: 98.0, vol: 0.19 },
  { symbol: "MS", name: "Morgan Stanley", base: 125.0, vol: 0.23 },
  { symbol: "MSFT", name: "Microsoft Corporation", base: 428.9, vol: 0.24 },
  { symbol: "MU", name: "Micron Technology Inc.", base: 105.0, vol: 0.42 },
  { symbol: "NDAQ", name: "Nasdaq Inc.", base: 89.0, vol: 0.22 },
  { symbol: "NFLX", name: "Netflix Inc.", base: 780.0, vol: 0.32 },
  { symbol: "NKE", name: "Nike Inc.", base: 78.0, vol: 0.27 },
  { symbol: "NOW", name: "ServiceNow Inc.", base: 1020.0, vol: 0.29 },
  { symbol: "NVDA", name: "NVIDIA Corporation", base: 138.2, vol: 0.48 },
  { symbol: "ORCL", name: "Oracle Corporation", base: 180.0, vol: 0.28 },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", base: 195.0, vol: 0.31 },
  { symbol: "PEP", name: "PepsiCo Inc.", base: 152.0, vol: 0.15 },
  { symbol: "PFE", name: "Pfizer Inc.", base: 26.0, vol: 0.2 },
  { symbol: "PG", name: "The Procter & Gamble Company", base: 168.0, vol: 0.14 },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", base: 68.3, vol: 0.62 },
  { symbol: "PNC", name: "The PNC Financial Services Group Inc.", base: 195.0, vol: 0.22 },
  { symbol: "QCOM", name: "QUALCOMM Inc.", base: 165.0, vol: 0.3 },
  { symbol: "QQQ", name: "Invesco QQQ Trust", base: 512.6, vol: 0.19 },
  { symbol: "RTX", name: "RTX Corporation", base: 122.0, vol: 0.2 },
  { symbol: "SBUX", name: "Starbucks Corporation", base: 95.0, vol: 0.22 },
  { symbol: "SCHW", name: "The Charles Schwab Corporation", base: 78.0, vol: 0.25 },
  { symbol: "SLB", name: "Schlumberger Limited", base: 42.0, vol: 0.28 },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", base: 254.9, vol: 0.35 },
  { symbol: "SPGI", name: "S&P Global Inc.", base: 520.0, vol: 0.19 },
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", base: 598.2, vol: 0.14 },
  { symbol: "T", name: "AT&T Inc.", base: 22.0, vol: 0.19 },
  { symbol: "TFC", name: "Truist Financial Corporation", base: 42.0, vol: 0.24 },
  { symbol: "TGT", name: "Target Corporation", base: 135.0, vol: 0.25 },
  { symbol: "TJX", name: "The TJX Companies Inc.", base: 122.0, vol: 0.17 },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", base: 550.0, vol: 0.19 },
  { symbol: "TSLA", name: "Tesla Inc.", base: 341.7, vol: 0.55 },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing", base: 198.4, vol: 0.33 },
  { symbol: "TXN", name: "Texas Instruments Inc.", base: 200.0, vol: 0.2 },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", base: 510.0, vol: 0.22 },
  { symbol: "UNP", name: "Union Pacific Corporation", base: 235.0, vol: 0.18 },
  { symbol: "UPS", name: "United Parcel Service Inc.", base: 128.0, vol: 0.22 },
  { symbol: "USB", name: "U.S. Bancorp", base: 48.0, vol: 0.23 },
  { symbol: "V", name: "Visa Inc.", base: 312.7, vol: 0.19 },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF", base: 296.4, vol: 0.14 },
  { symbol: "VZ", name: "Verizon Communications Inc.", base: 40.0, vol: 0.16 },
  { symbol: "WFC", name: "Wells Fargo & Company", base: 68.0, vol: 0.23 },
  { symbol: "WMT", name: "Walmart Inc.", base: 92.8, vol: 0.18 },
  { symbol: "XOM", name: "Exxon Mobil Corporation", base: 115.0, vol: 0.21 },
  { symbol: "YUM", name: "Yum! Brands Inc.", base: 138.0, vol: 0.16 },
];

/** The instrument the S&P 500 benchmark competitor tracks. */
export const BENCHMARK_SYMBOL = "SPY";

export const INSTRUMENT_BY_SYMBOL = new Map(
  INSTRUMENTS.map((i) => [i.symbol, i] as const),
);
